config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  post   '/contactme', to: 'static_pages#contactme'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users,               except: [:new] do
  #resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
  def contactme
    # Sends email to owner.
    if params[:body].empty?
      flash[:danger]= "Please write your concern."
      render 'contact'
    else
      UserMailer.sendme_mail(params[:body], current_user).deliver_now
      redirect_to root_url
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This is a template application for rails projects.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<div>
  <pre>You can send me a message below.</pre></br>
  <%= form_tag(contactme_path) do -%>
    Message: <%= text_area_tag "body", nil, :rows => 10 %>
    <%= submit_tag "Send", :id => 'contactme', :class => "btn btn-primary", :style => "width:100px;" %>
  <% end -%>
</div>

<script type="text/javascript">
  if($('#body').val() ==  "") 
   $('#contactme').attr('disabled', true);

  $('#body').keyup(function(){
    if($('#body').val() !=  "") 
         $('#contactme').attr('disabled', false);    
    else
         $('#contactme').attr('disabled', true);   
  });
</script>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  This page is under construction.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to Tickleup</h1>

    <h2>
      This is a template for rails projects.
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails logo"),
              'https://template-tickleup.herokuapp.com/' %>
<% end %>